name: default

type: docker
kind: pipeline

steps:
  - name: Build & Test
    image: python:3-alpine
    commands:
      - pip install -r requirements.txt
      - pytest
    when:
      - pull_request